export function getMockDailyReadingData() {
    return {
        "psalm": {
            "number": 51,
            "content": "Have mercy upon me, O God, according to Your lovingkindness; According to the multitude of Your tender mercies, blot out my transgressions. Wash me thoroughly from my iniquity, And cleanse me from my sin. For I acknowledge my transgressions, And my sin is always before me. Against You, You only, have I sinned, And done this evil in Your sight— That You may be found just when You speak, And blameless when You judge. Behold, I was brought forth in iniquity, And in sin my mother conceived me. Behold, You desire truth in the inward parts, And in the hidden part You will make me to know wisdom. Purge me with hyssop, and I shall be clean; Wash me, and I shall be whiter than snow. Make me hear joy and gladness, That the bones You have broken may rejoice. Hide Your face from my sins, And blot out all my iniquities. Create in me a clean heart, O God, And renew a steadfast spirit within me. Do not cast me away from Your presence, And do not take Your Holy Spirit from me. Restore to me the joy of Your salvation, And uphold me by Your generous Spirit. Then I will teach transgressors Your ways, And sinners shall be converted to You. Deliver me from the guilt of bloodshed, O God, The God of my salvation, And my tongue shall sing aloud of Your righteousness. O Lord, open my lips, And my mouth shall show forth Your praise. For You do not desire sacrifice, or else I would give it; You do not delight in burnt offering. The sacrifices of God are a broken spirit, A broken and a contrite heart— These, O God, You will not despise. Do good in Your good pleasure to Zion; Build the walls of Jerusalem. Then You shall be pleased with the sacrifices of righteousness, With burnt offering and whole burnt offering; Then they shall offer bulls on Your altar."
        },
        "proverb": {
            "number": 13,
            "content": "A wise son heeds his father’s instruction, But a scoffer does not listen to rebuke. A man shall eat well by the fruit of his mouth, But the soul of the unfaithful feeds on violence. He who guards his mouth preserves his life, But he who opens wide his lips shall have destruction. The soul of a lazy man desires, and has nothing; But the soul of the diligent shall be made rich. A righteous man hates lying, But a wicked man is loathsome and comes to shame. Righteousness guards him whose way is blameless, But wickedness overthrows the sinner. There is one who makes himself rich, yet has nothing; And one who makes himself poor, yet has great riches. The ransom of a man’s life is his riches, But the poor does not hear rebuke. The light of the righteous rejoices, But the lamp of the wicked will be put out. By pride comes nothing but strife, But with the well-advised is wisdom. Wealth gained by dishonesty will be diminished, But he who gathers by labor will increase. Hope deferred makes the heart sick, But when the desire comes, it is a tree of life. He who despises the word will be destroyed, But he who fears the commandment will be rewarded. The law of the wise is a fountain of life, To turn one away from the snares of death. Good understanding gains favor, But the way of the unfaithful is hard. Every prudent man acts with knowledge, But a fool lays open his folly. A wicked messenger falls into trouble, But a faithful ambassador brings health. Poverty and shame will come to him who disdains correction, But he who regards a rebuke will be honored. A desire accomplished is sweet to the soul, But it is an abomination to fools to depart from evil. He who walks with wise men will be wise, But the companion of fools will be destroyed. Evil pursues sinners, But to the righteous, good shall be repaid. A good man leaves an inheritance to his children’s children, But the wealth of the sinner is stored up for the righteous. Much food is in the fallow ground of the poor, And for lack of justice there is waste. He who spares his rod hates his son, But he who loves him disciplines him promptly. The righteous eats to the satisfying of his soul, But the stomach of the wicked shall be in want."
        }
    }
}